[versions]
libgdx = "1.13.0"
gdx-vfx = "0.5.4"
logback = "1.5.12"
junit-platform = "1.11.3"
junit-jupiter = "5.11.4"
mockito = "5.14.2"
assertj = "3.26.3"

[libraries]
gdx-lwjgl3 = { group = "com.badlogicgames.gdx", name = "gdx-backend-lwjgl3", version.ref = "libgdx" }
gdx-freetype-platform = { group = "com.badlogicgames.gdx", name = "gdx-freetype-platform", version.ref = "libgdx"}
gdx = { group = "com.badlogicgames.gdx", name = "gdx", version.ref = "libgdx" }
gdx-platform = { group = "com.badlogicgames.gdx", name = "gdx-platform", version.ref = "libgdx"}
gdx-backend-headless = { group = "com.badlogicgames.gdx", name = "gdx-backend-headless", version.ref = "libgdx"}
vfx-core = { group = "com.crashinvaders.vfx", name = "gdx-vfx-core", version.ref = "gdx-vfx" }
vfx-effects = { group = "com.crashinvaders.vfx", name = "gdx-vfx-effects", version.ref = "gdx-vfx" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

[bundles]
junit = ["junit-platform", "junit-jupiter-api", "junit-jupiter-params"]
gdx-vfx = ["vfx-core", "vfx-effects"]